name = "siraya-mcp-worker"
main = "src/index.ts"
compatibility_date = "2026-07-15"

workers_dev = false

routes = [
  { pattern = "siraya-mcp.bruceatsiraya.xyz", custom_domain = true }
]

[vars]
SIRAYA_BASE_URL = "https://llm.siraya.ai/v1"

[[kv_namespaces]]
binding = "SIRAYA_REGISTRY"
id = "7f90e1d5c1fd4ba0857271f12b5caa46"
preview_id = "f49c57aad20c48fa988e213e04259f6c"

[triggers]
crons = ["0 18 * * *"]
